export const LOAD = 'features/starredRepos/LOAD'
export const LOAD_NEXT = 'features/starredRepos/LOAD_NEXT'
export const HANDLE_RESPONSE = 'features/starredRepos/HANDLE_RESPONSE'
export const HANDLE_NEXT_RESPONSE = 'features/starredRepos/HANDLE_NEXT_RESPONSE'
export const HANDLE_ERROR = 'features/starredRepos/HANDLE_ERROR'
